// =====================================================================
// 夜读 v2 — entries (tech-focused with life)
// =====================================================================

const ENTRIES = [
  {
    id: "001",
    num: "Nº 047",
    title: "用了半年 RSC",
    titleEm: "之后",
    date: "2026.05.21",
    dateLong: "二〇二六 · 五月廿一",
    year: 2026,
    cat: "技术",
    tags: ["React", "Next.js", "架构"],
    reads: "12 min",
    words: 4280,
    dek: "Server Components 不是银弹，但它确实改变了我思考前端边界的方式。这是六个月生产环境实践之后的一些观察。",
    featured: true,
    codePeek: { k: "async function", f: "Page() {", c: "// RSC by default" },
    body: [
      { type: "lead", text: "去年十一月，我把一个中型 dashboard 从 Pages Router 迁到 App Router，全量启用 RSC。半年过去了，团队从最初的怀疑变成了基本依赖。但这条路远不像官方文档里那么平滑——这篇是把踩过的坑和真正赚到的东西一起写下来。" },
      { type: "h2", num: "01", text: "心智模型的转变" },
      { type: "p", text: "我以前会下意识地问：「这个组件要不要 useEffect 去拉数据？」现在我会先问：「这个组件能不能不变成 client component？」这两个问题的方向是反的。前者把数据当成异步资源，后者把数据当成属性。" },
      { type: "p", text: "一旦你接受了「服务端是默认值」，整个文件夹的设计都会改变。我现在通常一个路由下只有 1-2 个标 'use client' 的叶子组件，其余都是 server-only。" },
      { type: "quote", text: "RSC 真正的价值不在性能，而在于它让数据获取和组件树第一次成为同一件事。" },
      { type: "h2", num: "02", text: "三个用得最顺手的模式" },
      { type: "p", text: "经过几次重构，下面三个模式在我手上沉淀下来：" },
      { type: "code", lang: "tsx", code: "// 模式 1：把 client component 当作 \"shell\"\n<UploadProvider>           // 'use client'\n  <UploadList items={...} /> // server, 拿到数据后渲染\n</UploadProvider>" },
      { type: "p", text: "客户端组件做交互、状态、表单；服务端组件喂数据。这种 shell-and-slot 结构非常清晰。" },
      { type: "code", lang: "tsx", code: "// 模式 2：用 async server component 替代 SWR / React Query\nasync function Articles({ tag }: Props) {\n  const items = await db.articles.byTag(tag)\n  return <ArticleList items={items} />\n}" },
      { type: "callout", icon: "TIP", text: "**经验值**：能不能直接 await 取数，往往是判断「需不需要 use client」的最有用启发式。" },
      { type: "h2", num: "03", text: "踩过的真坑" },
      { type: "p", text: "Server Actions 的 revalidation 行为非常依赖你对缓存层的理解。我有一次因为 revalidatePath 写错了路径，整整两个小时找不到为什么 UI 不更新——但 network tab 里数据明明回来了。教训是：在 Next.js 里 cache 不是一层而是四层（fetch、Router、Full Route、Data），错位调试会让你怀疑人生。" },
      { type: "p", text: "另一个反复掉进去的是 hydration mismatch。任何在 server / client 都执行的逻辑都要假设两边的时钟、locale、随机数源都可能不同。我的笨办法是把所有这类逻辑挪到 useEffect。" },
      { type: "h2", num: "04", text: "如果让我再选一次" },
      { type: "p", text: "会。即便有一切折腾，最终代码量减少了大概 30%，包括之前手写的所有 cache key 管理、loading state、error boundary 重复样板。" },
      { type: "p", text: "但我不会建议任何团队为了「跟上潮流」迁。如果你现有的客户端架构能稳定跑业务，没必要。RSC 真正适合的是数据驱动密度高的 SaaS、内部工具、内容站点这种场景。" },
      { type: "hr" },
      { type: "p", text: "下一篇我准备写写 Server Actions 和表单的具体配方，包括我后来才发现的几个有用 hack。" },
    ],
  },
  {
    id: "002",
    num: "Nº 046",
    title: "用 Cloudflare Workers",
    titleEm: "搭一个 RSS 中转",
    date: "2026.05.14",
    dateLong: "二〇二六 · 五月十四",
    year: 2026,
    cat: "工具",
    tags: ["Cloudflare", "RSS", "Workers"],
    reads: "10 min",
    dek: "一个 100 行的 Worker，加上一个 KV，就能解决我所有的订阅去广告、合并、改写需求。",
  },
  {
    id: "003",
    num: "Nº 045",
    title: "为什么我换回了",
    titleEm: "Vim",
    date: "2026.05.07",
    dateLong: "二〇二六 · 五月七日",
    year: 2026,
    cat: "工具",
    tags: ["Vim", "工作流", "AI"],
    reads: "8 min",
    dek: "AI 编辑器很好用，但有些东西它替代不了。这篇是我作为一个十年 Vim 用户的折返跑。",
  },
  {
    id: "004",
    num: "Nº 044",
    title: "在咖啡店里 debug",
    titleEm: "了三小时",
    date: "2026.04.28",
    dateLong: "二〇二六 · 四月廿八",
    year: 2026,
    cat: "生活",
    tags: ["生活", "随笔"],
    reads: "5 min",
    dek: "周末换了家咖啡店，结果代码不工作。换回家里又工作。罪魁祸首竟然是咖啡店 wifi 把我的系统时间偏移了 11 秒。",
  },
  {
    id: "005",
    num: "Nº 043",
    title: "VS Code 工作流",
    titleEm: "五个必装的小插件",
    date: "2026.04.19",
    dateLong: "二〇二六 · 四月十九",
    year: 2026,
    cat: "工具",
    tags: ["VS Code", "效率"],
    reads: "7 min",
    dek: "排除 Copilot、Prettier 这种人人都装的，我有五个真正影响我每天写代码体验的小插件。",
  },
  {
    id: "006",
    num: "Nº 042",
    title: "在京都做开发者",
    titleEm: "的两周",
    date: "2026.04.11",
    dateLong: "二〇二六 · 四月十一",
    year: 2026,
    cat: "生活",
    tags: ["旅行", "远程"],
    reads: "9 min",
    dek: "鸭川边的咖啡馆、深夜的便利店、清晨的电车——以及为什么我没法在那里长期工作。",
  },
  {
    id: "007",
    num: "Nº 041",
    title: "对 Claude 4.5 Haiku",
    titleEm: "的使用心得",
    date: "2026.03.29",
    dateLong: "二〇二六 · 三月廿九",
    year: 2026,
    cat: "技术",
    tags: ["AI", "LLM"],
    reads: "11 min",
    dek: "用了一个月之后的一些真实感受，包括它在哪些任务上意外强，哪些任务上让我失望。",
  },
  {
    id: "008",
    num: "Nº 040",
    title: "类型安全的环境变量",
    titleEm: "monorepo 经验",
    date: "2026.03.15",
    dateLong: "二〇二六 · 三月十五",
    year: 2026,
    cat: "技术",
    tags: ["TypeScript", "DX"],
    reads: "13 min",
    dek: "用 Zod + Vite plugin 把 process.env 变成一等公民，再也不用半夜被「undefined is not a function」叫醒。",
  },
  {
    id: "009",
    num: "Nº 039",
    title: "三十岁那年我开始",
    titleEm: "写晨间日记",
    date: "2026.03.02",
    dateLong: "二〇二六 · 三月二日",
    year: 2026,
    cat: "生活",
    tags: ["生活", "习惯"],
    reads: "6 min",
    dek: "和写代码不一样，写日记不需要正确，只需要诚实。这件事的难点和回报都在这里。",
  },
  {
    id: "010",
    num: "Nº 038",
    title: "平安夜的最后",
    titleEm: "一班地铁",
    date: "2025.12.24",
    dateLong: "二〇二五 · 十二月廿四",
    year: 2025,
    cat: "生活",
    tags: ["随笔"],
    reads: "5 min",
    dek: "车厢里只有四个人。每个人都在低头看手机，但谁也没有真的在看。",
  },
  {
    id: "011",
    num: "Nº 037",
    title: "重读《追忆似水年华》",
    titleEm: "的第三遍",
    date: "2025.11.11",
    dateLong: "二〇二五 · 十一月十一",
    year: 2025,
    cat: "阅读",
    tags: ["读书"],
    reads: "11 min",
    dek: "第三遍。每一遍都是不一样的书，每一遍都是不一样的我。",
  },
  {
    id: "012",
    num: "Nº 036",
    title: "霜降之后",
    date: "2025.10.23",
    dateLong: "二〇二五 · 霜降",
    year: 2025,
    cat: "生活",
    tags: ["节气"],
    reads: "5 min",
    dek: "院子里的柿子终于红透了。今年没有人来摘，鸟也少了。",
  },
];

// Aggregate categories
const _cats = {};
ENTRIES.forEach(e => { _cats[e.cat] = (_cats[e.cat] || 0) + 1; });

const CATEGORIES = [
  { key: "技术", desc: "工程实践 / 架构思考", count: _cats["技术"] || 0 },
  { key: "工具", desc: "提升工作流的小器物", count: _cats["工具"] || 0 },
  { key: "生活", desc: "屏幕之外的事", count: _cats["生活"] || 0 },
  { key: "阅读", desc: "在读的与读过的", count: _cats["阅读"] || 0 },
];

const FILTERS = ["全部", "技术", "工具", "生活", "阅读"];

window.ENTRIES = ENTRIES;
window.CATEGORIES = CATEGORIES;
window.FILTERS = FILTERS;
